### ISSUE TITLE
"Failed copying input tensor..." on fit() even with BATCH_SIZE=1

### ISSUE THREAD

**Issue by ghost** [EscVM/RAMS#13]
After preprocessing the default data, i'm trying to run the train_RAMS_network notebook.

When calling the fit() function, I'm getting an 
```InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.```

From what I could find, it means it was impossible to allocate enough GPU memory for the tensor, and decreasing batch size might help - unfortunately it didn't, I'm getting the same error even after decreasing it to 1. 
I'm using a GTX1660Ti and the script allocates about 4.7 out of 6GB of its RAM before the error, is there any way I can get it to run on this hardware?

**Comment by EscVM** [comment]
It's a pretty old GPU :) Which version of TF are you using?

**Comment by ghost** [comment]
I'm using TF 2.9.1 and Python 3.9.9

Edit: I have tried downgrading to different Tensorflow versions and made it work with 2.5.0! Thanks :)
