### ISSUE TITLE
Multi Band question

### ISSUE THREAD

**Issue by paugalles** [EscVM/RAMS#2]
Hello,

One perk I am interested in from your network is to deal with multiple bands at once.

I am trying to train and use the RAMS with multiband inputs (i.e. RGB).
After reading your [paper](https://www.mdpi.com/2072-4292/12/14/2207) and checking carefully your code I have realized that the architecture of the network is theoretically designed to work with multiple bands, however, since it was used by separated bands in the ESA competition, the present code is not suitable for multiband.

What I did so far is to rearrange the patches generation so that it has an additional dimension for the bands. My array of patches are ( N , 32, 32, 9, 3) Which is NxHxWxTxC

Then I changed [this](https://github.com/EscVM/RAMS/blob/fd104bf1ff69e48c62ecffdbf16b7f802f2aac21/utils/network.py#L110) line of code to `img_inputs = Input(shape=(None,None,channels,bands)) `

I observed how you expand dimension just after the input.([code here](https://github.com/EscVM/RAMS/blob/fd104bf1ff69e48c62ecffdbf16b7f802f2aac21/utils/network.py#L115)) Is this to add the extra Bands dimension? (in your case C=1 ?)

I have observed that the RTAB is hard-coded to 9, see [this line of code](https://github.com/EscVM/RAMS/blob/fd104bf1ff69e48c62ecffdbf16b7f802f2aac21/utils/network.py#L146). Following the paper I should set it to 9x3=27, right? Also, before this layer, I am resizeing (following the paper) to (NxHxWx(T·C)) 

Is there anything else that I am missing?
I am wondering if you have got another version of the code that is not hardcoded for single bands or if it is feasible to arrange it for multiple bands.

Many thanks for all your work, it is just fantastic,

pau

**Comment by paugalles** [comment]
> Hello,
> 
> One perk I am interested in from your network is to deal with multiple bands at once.
> 
> I am trying to train and use the RAMS with multiband inputs (i.e. RGB).
> After reading your [paper](https://www.mdpi.com/2072-4292/12/14/2207) and checking carefully your code I have realized that the architecture of the network is theoretically designed to work with multiple bands, however, since it was used by separated bands in the ESA competition, the present code is not suitable for multiband.
> 
> What I did so far is to rearrange the patches generation so that it has an additional dimension for the bands. My array of patches are ( N , 32, 32, 9, 3) Which is NxHxWxTxC
> 
> Then I changed [this](https://github.com/EscVM/RAMS/blob/fd104bf1ff69e48c62ecffdbf16b7f802f2aac21/utils/network.py#L110) line of code to `img_inputs = Input(shape=(None,None,channels,bands)) `
> 
> I observed how you expand dimension just after the input.([code here](https://github.com/EscVM/RAMS/blob/fd104bf1ff69e48c62ecffdbf16b7f802f2aac21/utils/network.py#L115)) Is this to add the extra Bands dimension? (in your case C=1 ?)
> 
> I have observed that the RTAB is hard-coded to 9, see [this line of code](https://github.com/EscVM/RAMS/blob/fd104bf1ff69e48c62ecffdbf16b7f802f2aac21/utils/network.py#L146). Following the paper I should set it to 9x3=27, right? Also, before this layer, I am resizeing (following the paper) to (NxHxWx(T·C))
> 
> Is there anything else that I am missing?
> I am wondering if you have got another version of the code that is not hardcoded for single bands or if it is feasible to arrange it for multiple bands.
> 
> Many thanks for all your work, it is just fantastic,
> 
> pau

**Comment by EscVM** [comment]
I'm sorry @paugalles, but I was on vacation. Actually, I'm still on vacation😂. Anyway, yes, you should be able to train RAMS with multiple bands without any problems.

> I observed how you expand dimension just after the input.(code here) Is this to add the extra Bands dimension? (in your case C=1 ?)

Yes, you can omit it if you already enter with three bands.

> I have observed that the RTAB is hard-coded to 9, see this line of code. Following the paper I should set it to 9x3=27, right? Also, before this layer, I am resizing (following the paper) to (NxHxWx(T·C))

Exactly!

> Is there anything else that I am missing?
I am wondering if you have got another version of the code that is not hardcoded for single bands or if it is feasible to arrange it for multiple bands.

Try it, and if everything is fine, you shouldn't have any errors. Yes, I've another version but was made for Video super-resolution.

Anyway, share whatever errors you'll encounter, and we'll fix them together :)
