### ISSUE TITLE
Submissions questions

### ISSUE THREAD

**Issue by Suanmd** [EscVM/RAMS#4]
Excuse me, what kind of files(in ZIP) need to submit in PROBA-V Super Resolution post mortem?
I have an account but don't know how to use it. Thank you!

**Comment by EscVM** [comment]
Hi @Suanmd!

You can find all information you need [here](https://kelvins.esa.int/proba-v-super-resolution/submission-rules/). Anyway, it is a zip folder with all 290 prediction images named in a precise way.

Finally, in the RAMS test [notebook](https://github.com/EscVM/RAMS/blob/master/test_RAMS_network.ipynb) you can find all the code you need to automatically create a submission.

If you have further questions, please let me know.

**Comment by Suanmd** [comment]
> Hi @Suanmd!
> 
> You can find all information you need [here](https://kelvins.esa.int/proba-v-super-resolution/submission-rules/). Anyway, it is a zip folder with all 290 prediction images named in a precise way.
> 
> Finally, in the RAMS test [notebook](https://github.com/EscVM/RAMS/blob/master/test_RAMS_network.ipynb) you can find all the code you need to automatically create a submission.
> 
> If you have further questions, please let me know.

Thanks very much!!!!

**Comment by EscVM** [comment]
Hi @Suanmd

**Comment by Suanmd** [comment]
Hi @EscVM !
Thank you for your work! I am working on a new framework to solve the MISR problem.
Since I am not deeply involved in this field, I would like to add some experiments to make my work more abundant.
I'd like to ask you, is there any other public dataset for satellite multi-image super-resolution.
Thank you!!
