### ISSUE TITLE
Ask for help ^ _ ^

### ISSUE THREAD

**Issue by Suanmd** [EscVM/RAMS#5]
Thank you for your work! I am working on a new framework to solve the MISR problem.
Since I am not deeply involved in this field, I would like to add some experiments to make my work more abundant.
I'd like to ask you, is there any other public dataset for satellite multi-image super-resolution.
Thank you!!

**Comment by EscVM** [comment]
Hi @Suanmd!

I saw your message last week, but then it disappeared 😂. Anyway, unfortunately, I cannot help you. For our work, we based all experimentation on the ESA Proba-V dataset. Multi-Image super-resolution with remote sensing data is a pretty niche work so far. In any case, if you find another similar dataset on the same task, we could add references to this repository and create a more extensive benchmark.

**Comment by Suanmd** [comment]
Hi @EscVM 
😂 I will try my best, 3Q~
