### ISSUE TITLE
Working on own dataset

### ISSUE THREAD

**Issue by bibuzz** [EscVM/RAMS#7]
Hello sir, 
I tried your algorithm with predefined probv dataset and it works fine. Thank you for the code sir.

I wanted to create my own dataset, so I made one HR and temporal several LRs LR000,LR001,LR002 etc..But I am not sure how to get the QM000.png, QM001.png (the quality maps) and the SM.png (status map). Is there any software where I can make them in batch? what's the difference between the quality map and the status map?. I read your paper, so it it like cloud and cloud shadows removal?, what else could be removed sir?

Am new to image domain so any explanation would be of great help

**Comment by EscVM** [comment]
Hi @bibuzz,

Thanks for your interest in our repository.

I think that you could find all your answer in [THIS](https://arxiv.org/abs/1907.01821) publication, where the authors of the Proba-V dataset have described which tools and pre-processing steps they applied to generate all data.

**Comment by bibuzz** [comment]
Thank you for the response. Beginning to read the paper. I have a doubt, If I don't include the status map and quality map for your algorithm, i mean remove that part of the code, then super resolution will not work?

**Comment by EscVM** [comment]
Yes, it will work perfectly fine.

**Comment by bibuzz** [comment]
For my dataset , its 10m 384x384 (HR) and 20m 192x192 (LRs),  so then scale is 2, I only have 4 temporal LRs at the moment

Is my settings for this step correct?
#-------------
# General Settings
#-------------
PATH_DATASET = 'dataset' # pre-processed dataset path
name_net = 'RAMS' # name of the network
LR_SIZE = 48 # pathces dimension
SCALE = 2 # upscale of the proba-v dataset is 3
HR_SIZE = LR_SIZE * SCALE # upscale of the dataset is 3
OVERLAP = 48 # overlap between pathces
CLEAN_PATH_PX = 0.85 # percentage of clean pixels to accept a patch
band = 'NIR' # choose the band for the training
checkpoint_dir = f'ckpt/{band}_{name_net}_retrain' # weights path
log_dir = 'logs' # tensorboard logs path
submission_dir = 'submission' # submission dir

and  
----
#-------------
# Network Settings
#-------------
FILTERS = 48 # features map in the network
KERNEL_SIZE = 3 # convolutional kernel size dimension (either 3D and 2D)
CHANNELS = 4 # number of temporal steps
R = 8 # attention compression
N = 12 # number of residual feature attention blocks
lr = 1e-4 # learning rate (Nadam optimizer)
BATCH_SIZE = 48 # batch size
EPOCHS_N = 120 # number of epochs

I am asking because I tried various combinations and the first patch of HR is not matching the first patch of LR visually in this step
# print first patch and check if LR is in accordance with HR
fig, ax = plt.subplots(1,2, figsize=(10,10))
ax[0].imshow(X_train_patches[0,:,:,0], cmap = 'gray')
ax[1].imshow(y_train_patches[0,:,:,0], cmap = 'gray')

**Comment by bibuzz** [comment]
Hello Sir,

I have removed the status map and quality maps and consider all my images(taken from sentinel2) to be cloud free and clear.

HR image - 10m resolution - 384x384
LR images - 20m resolution - 192x192 (scale 2)

I made patches and my first patch of HR matches first patch of LR, I skipped the clarity patches checks step .
But in this step I am getting error
----------------------------------
# build rams network
rams_network = RAMS(scale=SCALE, filters=FILTERS, 
                 kernel_size=KERNEL_SIZE, channels=CHANNELS, r=R, N=N)

the settings I gave were:
--------------------------
#-------------
# General Settings
#-------------
PATH_DATASET = 'dataset' # pre-processed dataset path
name_net = 'RAMS' # name of the network
LR_SIZE = 48 # pathces dimension
SCALE = 2 # upscale of the proba-v dataset is 3
HR_SIZE = LR_SIZE * SCALE # upscale of the dataset is 3
OVERLAP = 48 # overlap between pathces
CLEAN_PATH_PX = 0.85 # percentage of clean pixels to accept a patch
band = 'NIR' # choose the band for the training
checkpoint_dir = f'ckpt/{band}_{name_net}_retrain' # weights path
log_dir = 'logs' # tensorboard logs path
submission_dir = 'submission' # submission dir

#-------------
# Network Settings
#-------------
FILTERS = 48 # features map in the network
KERNEL_SIZE = 3 # convolutional kernel size dimension (either 3D and 2D)
CHANNELS = 4 # number of temporal steps
R = 8 # attention compression
N = 12 # number of residual feature attention blocks
lr = 1e-4 # learning rate (Nadam optimizer)
BATCH_SIZE = 48 # batch size
EPOCHS_N = 120 # number of epochs

This is the error I get 
----------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-221-3830eeacf81a> in <module>
      1 # build rams network
----> 2 rams_network = RAMS(scale=SCALE, filters=FILTERS, 
      3                  kernel_size=KERNEL_SIZE, channels=CHANNELS, r=R, N=N)

D:\SuperResolution\RAMS\utils\network.py in RAMS(scale, filters, kernel_size, channels, r, N)
    137 
    138     # Upscaling
--> 139     x = conv3d_weightnorm(scale ** 2, (3,3,3), padding='valid')(x)
    140     x = layers.Lambda(lambda x: x[...,0,:])(x)
    141     x = layers.Lambda(lambda x: tf.nn.depth_to_space(x, 3))(x)

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, *args, **kwargs)
    994     # >> model = tf.keras.Model(inputs, outputs)
    995     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
--> 996       return self._functional_construction_call(inputs, args, kwargs,
    997                                                 input_list)
    998 

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\keras\engine\base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1132         layer=self, inputs=inputs, build_graph=True, training=training_value):
   1133       # Check input assumptions set after layer building, e.g. input shape.
-> 1134       outputs = self._keras_tensor_symbolic_call(
   1135           inputs, input_masks, args, kwargs)
   1136 

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\keras\engine\base_layer.py in _keras_tensor_symbolic_call(self, inputs, input_masks, args, kwargs)
    865       return nest.map_structure(keras_tensor.KerasTensor, output_signature)
    866     else:
--> 867       return self._infer_output_signature(inputs, args, kwargs, input_masks)
    868 
    869   def _infer_output_signature(self, inputs, args, kwargs, input_masks):

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\keras\engine\base_layer.py in _infer_output_signature(self, inputs, args, kwargs, input_masks)
    905           self._maybe_build(inputs)
    906           inputs = self._maybe_cast_inputs(inputs)
--> 907           outputs = call_fn(inputs, *args, **kwargs)
    908 
    909         self._handle_activity_regularization(inputs, outputs)

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\autograph\impl\api.py in wrapper(*args, **kwargs)
    693       except Exception as e:  # pylint:disable=broad-except
    694         if hasattr(e, 'ag_error_metadata'):
--> 695           raise e.ag_error_metadata.to_exception(e)
    696         else:
    697           raise

ValueError: in user code:

    C:\Users\Upasana\miniconda2\envs\RAM\lib\site-packages\tensorflow_addons\layers\wrappers.py:152 call  *
        outputs = self.layer(inputs)
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\keras\engine\base_layer.py:1057 __call__  **
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\keras\layers\convolutional.py:253 call
        outputs = self._convolution_op(inputs, self.kernel)
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\ops\nn_ops.py:1131 convolution_v2
        return convolution_internal(
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\ops\nn_ops.py:1261 convolution_internal
        return op(
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\ops\nn_ops.py:3129 _conv3d_expanded_batch
        return gen_nn_ops.conv3d(
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\ops\gen_nn_ops.py:1425 conv3d
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\func_graph.py:599 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\ops.py:3561 _create_op_internal
        ret = Operation(
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\ops.py:2041 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    C:\Users\Upasana\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\ops.py:1883 _create_c_op
        raise ValueError(str(e))

    **ValueError: Negative dimension size caused by subtracting 3 from 2 for '{{node weight_normalization_421/compute_weights/conv3d_408/Conv3D}} = Conv3D[T=DT_FLOAT, data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1, 1]](Placeholder, weight_normalization_421/compute_weights/mul, ^weight_normalization_421/compute_weights/Identity)' with input shapes: [?,?,?,2,48], [3,3,3,48,4].**

Any help would be appreciated

**Comment by bibuzz** [comment]
I noticed in utils/network.py

#-------------
# Settings
#-------------
MEAN = 7433.6436 # mean of the proba-v dataset
STD = 2353.0723 # std of proba-v the dataset

Since I am using sentinel images and not of prob-v dataset, then the MEAN and STD will be different ? How do I calculate them?

**Comment by fsalv** [comment]
Hi @bibuzz!

> Any help would be appreciated

Please clone the repository again, there was an issue in how our code was managing an even number of temporal frames. Now it should work with your 4 channels. Anyway, note that out Temporal Reduction Block  works better with an odd number (minimum of 3), so you should consider adding a temporal step to your dataset.

> #-------------
MEAN = 7433.6436 # mean of the proba-v dataset
STD = 2353.0723 # std of proba-v the dataset </br>
Since I am using sentinel images and not of prob-v dataset, then the MEAN and STD will be different ? How do I calculate them?

Those two values are used in the normalization and denormalization layers and they were simply computed on all the training images of the dataset. Just compute mean and standard deviation of your images pixel values.
